"""creer_table_commentaire

Revision ID: 143377df74e0
Revises: c08889d417f1
Create Date: 2024-10-21 07:29:24.075144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '143377df74e0'
down_revision = 'c08889d417f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commentaire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commentaire')
    # ### end Alembic commands ###
