"""ajout du champ description

Revision ID: 25e91fecefdb
Revises: a0ae8b3df50d
Create Date: 2024-10-23 09:27:29.667418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25e91fecefdb'
down_revision = 'a0ae8b3df50d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
